# Generated by Django 2.2.4 on 2021-03-18 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='fractionalLotsAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='number',
            field=models.CharField(default=uuid.uuid4, max_length=50),
        ),
    ]
