# Generated by Django 2.2.4 on 2021-03-18 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0002_auto_20210318_0416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxlot',
            name='productType',
        ),
    ]
