# Generated by Django 2.2.4 on 2021-03-18 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0005_auto_20210318_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='lots.Portfolio'),
        ),
        migrations.AlterField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='lots.Account'),
        ),
        migrations.AlterField(
            model_name='taxlot',
            name='holding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxLots', to='lots.Holding'),
        ),
    ]
