# Generated by Django 2.2.4 on 2021-03-18 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lots', '0006_auto_20210318_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxlot',
            name='units',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
