version: "3.9"

services:
    db:
        image: mysql
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD}"
        volumes:
            - mysql:/var/lib/mysql
            - mysql_config:/etc/mysql
    web:
        build: 
            context: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./:/app
        ports:
            - 8000:8000
        depends_on:
            - db
    test:
        build:
            context: .
        depends_on: 
            - db
            - web
        command: python manage.py test LotDividerAPI
volumes:
    mysql:
    mysql_config: