# Generated by Django 2.2.4 on 2021-05-02 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('LotDividerAPI', '0002_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=50)),
                ('cusip', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(default=uuid.uuid4, max_length=50)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatedSecurities', to='LotDividerAPI.ProductType')),
            ],
        ),
    ]
