# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Set Up Python and activate
      - uses: actions/setup-python@v2
        with:
          python-version: 3

      # run virtual env
      - name: Start virtual environment (python 3)
        run: |
          python3 -m pip install --user virtualenv

      - name: Install virtual environment
        run: python -m venv env
        
      - name: run virtual environment
        run: source env/bin/activate

      - name: test output
        run: python hello.py


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it      
      - uses: actions/checkout@v2
          

      
      # # Build stack
      # - name: Build Stack
      #   run: docker-compose up -d
      
      # - name: test
      #   run: docker-compose run web python manage.py test
      # # Install Dependencies
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      
      # # Test
      # - name: Set up Python and Test
      #   run: python manage.py test LotDividerAPI
